services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

        Derhaeuptling\RegiondoBundle\Controller\AjaxController:
            calls:
                - [setBookingManager, ['@Derhaeuptling\RegiondoBundle\BookingManager']]

    Derhaeuptling\RegiondoBundle\Controller\CartController:
        arguments:
            - '@Derhaeuptling\RegiondoBundle\Cart'

    Derhaeuptling\RegiondoBundle\Controller\CheckoutController:
        arguments:
            - '@Derhaeuptling\RegiondoBundle\Cart'
            - '@Derhaeuptling\RegiondoBundle\Checkout'

    Derhaeuptling\RegiondoBundle\Controller\EventBookingController:
        arguments:
            - '@Derhaeuptling\RegiondoBundle\EventHelper'

    Derhaeuptling\RegiondoBundle\AssetsHelper:
        arguments:
            $bundleDir: 'bundles/derhaeuptlingregiondo'
            $rootDir: '%kernel.project_dir%'
            $useSources: '%kernel.debug%'

    Derhaeuptling\RegiondoBundle\BookingManager:
        arguments:
            - '@Derhaeuptling\RegiondoBundle\ClientFactory'
            - '@contao.framework'

    Derhaeuptling\RegiondoBundle\Cart:
        arguments:
            - '@Derhaeuptling\RegiondoBundle\BookingManager'
            - '@Derhaeuptling\RegiondoBundle\ClientFactory'
            - '@Derhaeuptling\RegiondoBundle\DataFormatter'

    Derhaeuptling\RegiondoBundle\Checkout:
        arguments:
            - '@Derhaeuptling\RegiondoBundle\BookingManager'

    Derhaeuptling\RegiondoBundle\DataFormatter:
        arguments:
            - '@contao.framework'

    Derhaeuptling\RegiondoBundle\EventHelper:
        arguments:
            - '@Derhaeuptling\RegiondoBundle\ClientFactory'
            - '@Derhaeuptling\RegiondoBundle\DataFormatter'

    Derhaeuptling\RegiondoBundle\Synchronizer:
        arguments:
            - '@Derhaeuptling\RegiondoBundle\ClientFactory'
            - '@database_connection'
            - '@logger'
        tags:
            - { name: monolog.logger, channel: regiondo }
